build: false

install:
  - cinst unity -version 5.0.1
  - cinst pester

test_script:
  - ps: $tests = Invoke-Pester -Path ".\PSUnity.Tests" -PassThru
  - ps: if ($tests.FailedCount -gt 0) { throw "$($tests.FailedCount) tests failed." }
